TGSIM = {
    "lava": {
        "IAT": 3,
        "IAW": 3,
        "IAC": 3,
        "WV": 3,
        "IRA": 4,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 4,
        "IIO":4
    },
    "mxm": {
        "IAT": 3,
        "IAW": 3,
        "IAC": 3,
        "WV": 3,
        "IRA": 3,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 3,
        "IIO":3
    },
    "gemm": {
        "IAT": 6,
        "IAW": 6,
        "IAC": 6,
        "WV": 6,
        "IRA": 6,
        "IAL": 6,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 6,
        "IIO":4
    },
    "hotspot": {
        "IAT": 4,
        "IAW": 4,
        "IAC": 4,
        "WV": 4,
        "IRA": 17,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 17,
        "IIO":17
    },
    "gaussian": {
        "IAT": 4,
        "IAW": 4,
        "IAC": 4,
        "WV": 4,
        "IRA": 6,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 6,
        "IIO":6
    },
    "bfs": {
        "IAT": 7,
        "IAW": 7,
        "IAC": 7,
        "WV": 12,
        "IRA": 61,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 61,
        "IIO":4
    },
    "lud": {
        "IAT": 4,
        "IAW": 4,
        "IAC": 4,
        "WV": 4,
        "IRA": 13,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 13,
        "IIO":13
    },
    "accl": {
        "IAT": 5,
        "IAW": 5,
        "IAC": 5,
        "WV": 5,
        "IRA": 7,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 7,
        "IIO":7
    },
    "nw": {
        "IAT": 5,
        "IAW": 5,
        "IAC": 5,
        "WV": 5,
        "IRA": 8,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 8,
        "IIO":8
    },
    "cfd": {
        "IAT": 5,
        "IAW": 5,
        "IAC": 5,
        "WV": 5,
        "IRA": 6,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 6,
        "IIO":6
    },
    "quicksort": {
        "IAT": 5,
        "IAW": 5,
        "IAC": 5,
        "WV": 5,
        "IRA": 6,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC":6,
        "IIO":6
    },
    "mergesort": {
        "IAT": 4,
        "IAW": 4,
        "IAC": 4,
        "WV": 4,
        "IRA": 5,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 5,
        "IIO":5
    },
    "VectorAdd": {
        "IAT": 3,
        "IAW": 3,
        "IAC": 3,
        "WV": 3,
        "IRA": 3,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 3,
        "IIO":3
    },
    "LeNet_pytorch": {
        "IAT": 3,
        "IAW": 3,
        "IAC": 3,
        "WV": 3,
        "IRA": 3,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 3,
        "IIO":3,
        "FUs":39,
        "REGs":35
    },
    "AlexNet_Conv2D_L0_BS32": {
        "IAT": 3,
        "IAW": 3,
        "IAC": 3,
        "WV": 3,
        "IRA": 3,
        "IMS":3,
        "IMD":3,
        "IAL":3,
        "ICOC": 3,
        "IIO":3,
        "FUs":39,
        "REGs":35
    }
}